dist: trusty
install:
  - npm install
language: node_js
node_js:
  - "8"
script:
  - npm run test
after_script:
  - mkdir reports
  - mv ./backstop_data/html_report ./reports/html_report_`date +%Y-%m-%d_%H-%M-%S`
  - mv ./backstop_data/ci_report ./reports/ci_report_`date +%Y-%m-%d_%H-%M-%S`

addons:
  chrome: stable
  artifacts:
    s3_region: "us-east-1"
    paths:
      - "./reports/"
    debug: true

