dist: trusty
install:
  - npm install
language: node_js
node_js:
  - "8"
script:
  - npm run test
after_script:
  - mkdir artifacts
  - tar -czf ./artifacts/report_`date +%Y-%m-%d_%H-%M-%S`.tar.gz ./backstop_data/html_report ./backstop_data/ci_report
addons:
  chrome: beta
env:
  - CHROME_PATH=/usr/bin/google-chrome-beta
deploy:
  provider: s3
  # access_key_id: "YOUR AWS ACCESS KEY"
  # secret_access_key: "YOUR AWS SECRET KEY"
  # bucket: "S3 Bucket"
  skip_cleanup: true
  acl: public_read
  local_dir: artifacts
