dist: trusty
install:
  - npm install
language: node_js
node_js:
  - "8"
script:
  - npm run test
after_script:
  - mkdir artifacts
  - tar -czf ./artifacts/report_`date +%Y-%m-%d_%H-%M-%S`.tar.gz ./backstop_data/html_report ./backstop_data/ci_report
addons:
  chrome: beta
  artifacts:
    s3_region: "us-east-1"
    paths:
      - "./artifacts/"
    debug: true
    acl: public_read
